version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: docker/run_web.sh
    restart: always
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
  db:
    ports:
      - "5432:5432"
    image: postgres:10-alpine
    env_file:
      - .env
    volumes:
      - vehicle-portal-db-data:/var/lib/postgresql/data/ # persist data even

  redis_db:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - .:/app
    env_file:
      - .env
    command: ./docker/run_celery.sh

  
volumes:
  vehicle-portal-db-data:
  