from django.contrib import admin
from .models.VehicleFamily import VehicleFamily
from .admin_sites.VehicleFamilyAdmin import VehicleFamilyAdmin
from .models.Vehicle import Vehicle
from .admin_sites.VehicleAdmin import VehicleAdmin
from .models.Assembly import Assembly
from .admin_sites.AssemblyAdmin import AssemblyAdmin
from .models.Subassembly import Subassembly
from .admin_sites.SubassemblyAdmin import SubassemblyAdmin
from .models.BOM import BOM
from .admin_sites.BOMAdmin import BOMAdmin
