# Generated by Django 3.1.1 on 2020-09-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20200903_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='is_made_locally',
            new_name='is_purchased',
        ),
        migrations.RemoveField(
            model_name='purchaseassembly',
            name='name',
        ),
    ]
