# Generated by Django 3.1.1 on 2020-09-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20200911_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseassembly',
            name='parts',
            field=models.ManyToManyField(related_name='purchase_assemblies', related_query_name='purchase_assembly', through='parts.PurchaseAssemblyPart', to='parts.Part'),
        ),
        migrations.AlterField(
            model_name='purchaseassemblypart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
        migrations.AlterField(
            model_name='purchaseassemblypart',
            name='purchase_assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.purchaseassembly'),
        ),
    ]
