# Generated by Django 3.1.1 on 2020-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20200915_1006'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseassembly',
            index=models.Index(fields=['code'], name='parts_purch_code_8dc610_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseassemblypart',
            index=models.Index(fields=['purchase_assembly'], name='parts_purch_purchas_0ab9fb_idx'),
        ),
    ]
