# Generated by Django 3.1.1 on 2020-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20201005_1555'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseassemblypart',
            name='unique_purchase_assembly_part',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='revision_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='part',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='part',
            name='is_available',
        ),
        migrations.AddIndex(
            model_name='purchaseassemblypart',
            index=models.Index(fields=['purchase_assembly', 'part', 'quantity'], name='parts_purch_purchas_b0701d_idx'),
        ),
    ]
