# Generated by Django 3.1.2 on 2020-11-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20201029_1140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0009_auto_20201006_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('supplier_part_number', models.TextField(blank=True)),
                ('purchase_comments', models.TextField(blank=True)),
                ('company', models.ForeignKey(help_text='Supplier company.', on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partsupplier_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partsupplier_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
            ],
            options={
                'verbose_name': 'part supplier',
                'verbose_name_plural': 'part suppliers',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='suppliers',
            field=models.ManyToManyField(related_name='parts', related_query_name='part', through='parts.PartSupplier', to='companies.Company'),
        ),
    ]
