# Generated by Django 3.1.5 on 2022-07-31 10:03

import django.core.validators
from django.db import migrations, models
import parts.models.Part
import parts.models.PurchaseAssembly


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20201103_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='code',
            field=models.PositiveIntegerField(default=parts.models.Part.Part.get_next_part_code, help_text='5 digit TG code.', validators=[django.core.validators.RegexValidator(code='nomatch', message='Code has to be 5 digits long.', regex='^\\d{5}$')], verbose_name='Part #'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='purchaseassembly',
            name='code',
            field=models.PositiveIntegerField(default=parts.models.PurchaseAssembly.PurchaseAssembly.get_next_purchase_assembly_code, help_text='PA code without the A prefix.', unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Code has to be 7 digits long.', regex='^\\d{7}$')], verbose_name='Purchase Assy #'),
        ),
    ]
