# Generated by Django 3.1.1 on 2020-09-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['company'], name='companies_l_company_4ebbce_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_supplier'], name='companies_c_is_supp_f952ec_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_customer'], name='companies_c_is_cust_2aabd1_idx'),
        ),
    ]
