# Generated by Django 3.1.2 on 2020-11-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20201103_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
    ]
