# Generated by Django 3.1.1 on 2020-09-15 16:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='4 digit assembly code. For example: 1010.', max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Code has to be 4 digits long.', regex='^\\d{4}$')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assembly',
                'verbose_name_plural': 'assemblies',
            },
        ),
        migrations.RemoveField(
            model_name='vehiclefamily',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='vehiclefamily',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclefamily',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Subassembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='Format: SXX, where XX is a number. For example: S01.', max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Code has to begin with S and be followed by 2 digits.', regex='^[S]{1}\\d{2}$')])),
                ('assembly', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vehicle_family', chained_model_field='vehicle_family', on_delete=django.db.models.deletion.CASCADE, related_name='subassemblies', related_query_name='subassembly', to='vehicles.assembly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subassembly_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subassembly_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('vehicle_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subassemblies', related_query_name='subassembly', to='vehicles.vehiclefamily')),
            ],
            options={
                'verbose_name': 'subassembly',
                'verbose_name_plural': 'subassemblies',
            },
        ),
        migrations.AddField(
            model_name='assembly',
            name='vehicle_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', related_query_name='assembly', to='vehicles.vehiclefamily'),
        ),
        migrations.AddConstraint(
            model_name='subassembly',
            constraint=models.UniqueConstraint(fields=('assembly', 'code'), name='unique_assembly_subassembly'),
        ),
        migrations.AddConstraint(
            model_name='assembly',
            constraint=models.UniqueConstraint(fields=('vehicle_family', 'code'), name='unique_vehiclefamily_assembly'),
        ),
    ]
