# Generated by Django 3.1.1 on 2020-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200915_1327'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['vehicle_family'], name='vehicles_as_vehicle_642c60_idx'),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['code'], name='vehicles_as_code_bc858b_idx'),
        ),
        migrations.AddIndex(
            model_name='subassembly',
            index=models.Index(fields=['assembly'], name='vehicles_su_assembl_f141cf_idx'),
        ),
        migrations.AddIndex(
            model_name='subassembly',
            index=models.Index(fields=['code'], name='vehicles_su_code_7ecd28_idx'),
        ),
    ]
