# Generated by Django 3.1.1 on 2020-09-21 20:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20200915_1435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_auto_20200915_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('revision', models.CharField(blank=True, help_text='Revision code. For example: A.', max_length=1)),
                ('revision_notes', models.TextField(blank=True)),
                ('import_file', models.FileField(upload_to='uploads/boms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('vehicle_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', related_query_name='bom', to='vehicles.vehiclefamily')),
            ],
            options={
                'verbose_name': 'Bill of materials',
                'verbose_name_plural': 'Bills of materials',
            },
        ),
        migrations.CreateModel(
            name='BOMRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Amount used in the BOM in this location.', validators=[django.core.validators.MinValueValidator(1)])),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_rows', related_query_name='bom_row', to='vehicles.assembly')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', related_query_name='row', to='vehicles.bom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bomrow_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bomrow_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rows', related_query_name='bom_row', to='parts.part')),
                ('purchase_assembly_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rows', related_query_name='bom_row', to='parts.purchaseassemblypart')),
                ('subassembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_rows', related_query_name='bom_row', to='vehicles.subassembly')),
            ],
            options={
                'verbose_name': 'Bill of materials row',
                'verbose_name_plural': 'Bill of materials rows',
            },
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('code', 'revision'), name='unique_bom_code_revision'),
        ),
    ]
