# Generated by Django 3.1.1 on 2020-09-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20200921_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='subassembly',
            name='full_code',
            field=models.CharField(blank=True, editable=False, max_length=7),
        ),
    ]
