# Generated by Django 3.1.2 on 2020-10-07 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_subassembly_full_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='import_file',
            field=models.FileField(upload_to='uploads/boms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xlsm', 'xls'])]),
        ),
    ]
