# Generated by Django 3.1.2 on 2020-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20201020_1811'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subassembly',
            index=models.Index(fields=['vehicle_family', 'full_code'], name='vehicles_su_vehicle_f2eb2f_idx'),
        ),
    ]
