# Generated by Django 3.1.2 on 2020-10-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20201023_1215'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['vehicle_family', 'code'], name='vehicles_as_vehicle_929103_idx'),
        ),
    ]
