# Generated by Django 3.1.2 on 2020-10-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20201029_1140'),
        ('vehicles', '0011_auto_20201029_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', related_query_name='vehicle', to='vehicles.bom', verbose_name='Bill of materials'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(help_text='Location where the customer has this vehicle.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', related_query_name='vehicle', to='companies.location'),
        ),
    ]
