# Generated by Django 3.1.2 on 2020-10-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_auto_20201029_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
