# Generated by Django 3.1.2 on 2020-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('vehicles', '0014_vehicle_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='files',
            field=models.ManyToManyField(to='files.File'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='files',
            field=models.ManyToManyField(to='files.File'),
        ),
    ]
