# Generated by Django 3.1.2 on 2020-11-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('vehicles', '0015_auto_20201104_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
    ]
