# Generated by Django 3.1.2 on 2020-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('vehicles', '0016_auto_20201104_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='General files related to the BOM.', to='files.File'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='General files related to the vehicle.', to='files.File'),
        ),
    ]
