# Generated by Django 3.1.2 on 2020-10-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0005_auto_20201029_1140'),
        ('vehicles', '0013_auto_20201029_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('CREATED', 'Created'), ('REVIEWED', 'Reviewed')], default='CREATED', max_length=15)),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('company_code', models.CharField(blank=True, max_length=25)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.cart')),
                ('company', models.ForeignKey(help_text='Customer company related to this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CartRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('vehicle_identification_number', models.CharField(blank=True, max_length=20)),
                ('bom_name', models.CharField(blank=True, max_length=75)),
                ('bom_code', models.CharField(blank=True, max_length=25)),
                ('bom_revision', models.CharField(blank=True, max_length=5)),
                ('assembly_name', models.CharField(blank=True, max_length=75)),
                ('assembly_code', models.CharField(blank=True, max_length=5)),
                ('subassembly_name', models.CharField(blank=True, max_length=75)),
                ('subassembly_full_code', models.CharField(blank=True, max_length=10)),
                ('purchase_assembly_full_code', models.CharField(blank=True, max_length=10)),
                ('part_name', models.CharField(blank=True, max_length=200)),
                ('part_full_code', models.CharField(blank=True, max_length=15)),
                ('part_uses', models.CharField(blank=True, max_length=3)),
                ('bom_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_rows', related_query_name='cart_row', to='vehicles.bomrow')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', related_query_name='row', to='orders.cart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartrow_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartrow_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_rows', related_query_name='cart_row', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'cart row',
                'verbose_name_plural': 'cart rows',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_username'], name='orders_orde_user_us_8a7103_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_email'], name='orders_orde_user_em_a805c0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company_name'], name='orders_orde_company_cc8347_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company_code'], name='orders_orde_company_d8133e_idx'),
        ),
        migrations.AddIndex(
            model_name='cartrow',
            index=models.Index(fields=['cart'], name='orders_cart_cart_id_cf7b4e_idx'),
        ),
    ]
