# Generated by Django 3.1.2 on 2020-10-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrow',
            name='vehicle_nickname',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
