# Generated by Django 3.1.2 on 2020-11-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartrow_vehicle_nickname'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_company_d8133e_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_code',
        ),
    ]
