# Generated by Django 3.1.2 on 2020-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201103_1152'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_current', 'created_by'], name='orders_cart_is_curr_19bd90_idx'),
        ),
        migrations.AddIndex(
            model_name='cartrow',
            index=models.Index(fields=['cart', 'vehicle', 'bom_row'], name='orders_cart_cart_id_b3803c_idx'),
        ),
    ]
