# Generated by Django 3.1.2 on 2020-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201119_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrow',
            name='assembly_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='assembly_name',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='bom_code',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='bom_name',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='bom_revision',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='part_full_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='part_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='part_uses',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='purchase_assembly_full_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='subassembly_full_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='subassembly_name',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='vehicle_identification_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartrow',
            name='vehicle_nickname',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
